<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <AssemblyName>CelesteNet.Client</AssemblyName>
    <RootNamespace>Celeste.Mod.CelesteNet.Client</RootNamespace>
      <!-->Nullable>disable</Nullable-->
  </PropertyGroup>

  <Import Project="..\CelesteNet.props" />

  <ItemGroup>
    <Compile Remove="RPC\**" />
    <EmbeddedResource Remove="RPC\**" />
    <None Remove="RPC\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CelesteNet.Shared\CelesteNet.Shared.csproj" />
  </ItemGroup>
  
</Project>
